# CI build with the upload to MyGet

variables:
  DotNetVersion: "2.1.402"

trigger:
  branches:
    include:
    - master
    - develop

queue: Hosted VS2017
steps:
- task: DotNetCoreInstaller@0
  displayName: force use of desired dotnet version
  inputs:
    version: $(DotNetVersion)

- task: DotNetCoreCLI@2
  displayName: restore packages
  inputs:
    command: "restore"
    projects: "*.sln"

- task: DotNetCoreCLI@2
  displayName: build solution (Release)
  inputs:
    command: "build"
    projects: "*.sln"
    arguments: "--configuration Release"

- task: DotNetCoreCLI@2
  displayName: pack solution (Release)
  inputs:
    command: "pack"
    projects: "*.sln"
    configuration: 'Release'
    packDirectory: '$(build.artifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: "test"
    projects: "test/**/*.Tests.csproj"
    arguments: "--configuration Release"

- task: PublishTestResults@2

- task: DotNetCoreCLI@1
  displayName: publish
  inputs:
    command: "publish"
    publishWebProjects: "True"
    arguments: "--configuration Release --output $(build.artifactstagingdirectory)"
    zipAfterPublish: "True"

- task: NuGetCommand@2
  displayName: 'Publish nugets to MyGet'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'myget-open-census'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "$(build.artifactstagingdirectory)"
    ArtifactName: "drop"
    ArtifactType: "Container"